name: Carlos Lopes
favicon: null
layout_spectrum: 0.9673182067926973
typography_spectrum: 0.9704327345825732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09137094835750759
  lightness: 0.6614063230808824
  saturation: 0.9267210259567946
  rhythmicContrast: 0.7999583536293358
purpose: []
